### ISSUE TITLE
Käyttöliittymän alustava suunnittelu

### ISSUE THREAD

**Issue by kkuismin** [kkuismin/kkvvrsolutions-ticketguru#4]

**Comment by perttuvirkki** [comment]
Käyttöliittymää hahmoteltu alustavasti


![Image](https://github.com/kkuismin/kkvvrsolutions-ticketguru/assets/98482404/7e845650-29db-486b-8856-79bb25c517f7)



![Image](https://github.com/kkuismin/kkvvrsolutions-ticketguru/assets/98482404/a1e0ee36-e664-41c2-a26d-4024920a71b6)



![Image](https://github.com/kkuismin/kkvvrsolutions-ticketguru/assets/98482404/e1470bdb-af36-4f17-a945-09c0aedea3c5)
